version: "3.7"

services:
  mysql-jam:
    image: mariadb:10.3
    ports:
      - "33066:3306"
    restart: always
    volumes:
      - type: bind
        source: ./docker/mysql/mysql_custom.cnf
        target: /etc/mysql/conf.d/mysql_custom.cnf
      - type: volume
        source: jam_db_data
        target: /var/lib/mysql
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file: .env
    networks:
      - jam_network

  php-jam:
    container_name: php-jam
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile-8-0-3
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./
        target: /var/www/jam-backend
    working_dir: /var/www/jam-backend
    env_file: .env
    networks:
      - jam_network

  nginx-jam:
    container_name: nginx-jam
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8820:80"
      - "8821:81"
    volumes:
      - type: bind
        source: ./docker/nginx/sites
        target: /etc/nginx/templates
      - type: bind
        source: ./
        target: /var/www/jam-backend
    env_file: .env
    networks:
      - jam_network

  redis-jam:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - jam_network


networks:
  jam_network:
    name: jam_network
    driver: bridge

volumes:
  jam_db_data:
    driver: local
